### PR TITLE
Cross validation.predict proba.single cross val predict apply tests and doc

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
@merritts ping

**Comment by ghost** [comment]
can you please push to https://github.com/scikit-learn/scikit-learn/pull/5127#issuecomment-191775798 ?

**Comment by ghost** [comment]
@merritts ping ? :) can you please push to the main repo PR?

**Comment by merritts** [comment]
@orizdy, I believe your code is being pushed automatically when I merge. If you look at my pull request you can see your commits. https://github.com/scikit-learn/scikit-learn/pull/5127

Let me know if I need to rebase or if the failed tests are from your new changes.

**Comment by ghost** [comment]
the newest changes of this PR are not at scikit-learn#5127.

**Comment by ghost** [comment]
Don't you need to push it to main repo too?

**Comment by merritts** [comment]
No. All the changes need to be merged into the predict_proba branch. Can you add these to that branch?

**Pull request merged**
